name: generate-content-files
on: [push]
jobs:
  generate-content-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: list working directory
        run: |
            ls ${{ github.workspace }}
            ls ${{ github.workspace }}/src
      - name: push a file with content info
        run: |
          ls ${{ github.workspace }}/contents > fileInfo.txt
          git config --global user.email "devops@github.com"
          git config --global user.name "github-actions-bot"
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/AllenAnZifeng/blog_content.git
          git diff --exit-code || (git add fileInfo.txt && git commit -m "Automated report" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy-md-book:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Install mdbook
          run: |
            mkdir mdbook
            curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.14/mdbook-v0.4.14-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=./mdbook
            echo `pwd`/mdbook >> $GITHUB_PATH
        - name: Deploy GitHub Pages
          run: |
            # This assumes your book is in the root of your repository.
            # Just add a `cd` here if you need to change to another directory.
            mdbook build
            git worktree add gh-pages
            git config user.name "Deploy from CI"
            git config user.email ""
            cd gh-pages
            # Delete the ref to avoid keeping history.
            git update-ref -d refs/heads/gh-pages
            rm -rf *
            mv ../book/* .
            git add .
            git commit -m "Deploy $GITHUB_SHA to gh-pages"
            git push --force --set-upstream origin gh-pages